{{- if and .Values.serviceAccount.create .Values.serviceAccount.createAndBindRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spicedb.serviceAccountName" . }}-kuberesolver-access
roleRef:
  kind: Role
  name: watchEndpoints
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "spicedb.serviceAccountName" . }}
  namespace: {{ Release.Namespace }}
{{- end }}
